---
# Grype configuration file for container vulnerability scanning
# https://oss.anchore.com/docs/reference/grype/configuration/

ignore:
  - vulnerability: CVE-2026-7210
  # Patched upstream, awaiting base image update - see README on how to check for updates.
  - vulnerability: CVE-2026-9669
  # vuln coming from aws cli bundled python - cannot bump python version independently
  - vulnerability: CVE-2026-15308
  - vulnerability: CVE-2026-11940
  - vulnerability: CVE-2026-11972

  # transitive dependency - waiting for base image update
  - vulnerability: CVE-2026-40355
  - vulnerability: CVE-2026-40356
  - vulnerability: CVE-2026-59850  # libssh-4
  - vulnerability: CVE-2026-59847  # libssh-4
  - vulnerability: CVE-2026-54371  # libattr1
