---
name: 🩻 Container Scan

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  container-scan:
    permissions:
      contents: read
      id-token: write
      pull-requests: write
      security-events: write
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@feat/grype-scanning # v5.1.0
    with:
      runtime: python
