---
name: 🩻 Container Scan

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  id-token: write

jobs:
  container-scan:
    name: Container Scan
    uses: ministryofjustice/analytical-platform-airflow-github-actions/.github/workflows/shared-scan-container.yml@feat/grype-scanning # v5.1.0
    with:
      runtime: python
